name: CI-Cygwin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install cygwin base packages with chocolatey
      shell: pwsh
      run: |
        choco install --no-progress cygwin --version 3.1.7
        choco install cyg-get

    - name: Ensure scripts are unix compatible
      run: dos2unix deploy.sh

    - name: Running setup
      run: C:\tools\cygwin\bin\bash.exe deploy.sh setup

    - name: Re-running setup with trace enabled
      run: C:\tools\cygwin\bin\bash.exe deploy.sh setup -trace

